export const categories = [
  {
    title: 'Marriage',
    backgroundColor: '#FFE0E0',
    icon: '💍',
    onPress: () => {},
    img: require('../../assets/imgs/category/marriage.jpg'),
  },
  {
    title: 'Career',
    backgroundColor: '#E0F0FF',
    icon: '📈',
    onPress: () => {},
    img: require('../../assets/imgs/category/career.webp'),
  },
  {
    title: 'Education',
    backgroundColor: '#E7F4D9',
    icon: '🎓',
    onPress: () => {},
    img: require('../../assets/imgs/category/education.webp'),
  },
  {
    title: 'Health',
    backgroundColor: '#FDE7E7',
    icon: '🩺',
    onPress: () => {},
    img: require('../../assets/imgs/category/health.jpeg'),
  },
  {
    title: 'Family',
    backgroundColor: '#FFE4C4',
    icon: '👪',
    onPress: () => {},
    img: require('../../assets/imgs/category/family.jpg'),
  },
  {
    title: 'Money',
    backgroundColor: '#D1F7C4',
    icon: '💰',
    onPress: () => {},
    img: require('../../assets/imgs/category/money.jpeg'),
  },
  {
    title: 'Vastu Shastra',
    backgroundColor: '#FDE1FF',
    icon: '🏠',
    onPress: () => {},
    img: require('../../assets/imgs/category/vastu-sastra.jpeg'),
  },
  {
    title: 'Kundli Matching',
    backgroundColor: '#CDEBFF',
    icon: '📜',
    onPress: () => {},
    img: require('../../assets/imgs/category/Kundli-Matching.jpeg'),
  },
  {
    title: 'Relationship',
    backgroundColor: '#FFD6D6',
    icon: '❤️',
    onPress: () => {},
    img: require('../../assets/imgs/category/relationship.jpg'),
  },
  {
    title: 'VIP E-Pooja',
    backgroundColor: '#FFF0B3',
    icon: '🪔',
    onPress: () => {},
    img: require('../../assets/imgs/category/VIP-E-Pooja.jpeg'),
  },
  {
    title: 'Name Correction',
    backgroundColor: '#E1E1FF',
    icon: '✍️',
    onPress: () => {},
    img: require('../../assets/imgs/category/name-correction.jpeg'),
  },
  {
    title: 'Numberology',
    backgroundColor: '#FFC0CB',
    icon: '💞',
    onPress: () => {},
    img: require('../../assets/imgs/category/numberology.jpeg'),
  },
];
